---
inputs:
- type: git
  branch: dual-template
  service: ${APP_REPO}
  path: .tekton
- type: git
  branch: master
  service: ${TEKTON_CATALOG_REPO}
  path: git
triggers:
- type: manual
  name: Create Validate Key
  eventListener: key-validate-listener
- type: manual
  name: Create Build Key
  eventListener: key-build-listener
- type: manual
  name: Delete Build Key
  eventListener: key-delete-build-listener
- type: manual
  name: Delete Validate Key
  eventListener: key-delete-validate-listener
properties:
- name: api-key
  value: ${API_KEY}
  type: SECURE
- name: repository-integration
  value: app-repo
  type: text
- name: repository
  value: ${APP_REPO_FULL}
  type: text
- name: branch
  value: dual-template
  type: text
- name: registry-namespace
  value: ${REGISTRY_NAMESPACE}
  type: text
- name: region
  value: ${DEV_REGION_ID}
  type: text
- name: resource-group
  value: ${DEV_RESOURCE_GROUP}
  type: text
- name: validation-signer
  value: ${VALIDATION_SIGNER}
  type: text
- name: build-signer
  value: ${BUILD_SIGNER}
  type: text
- name: vault-name
  value: ${VAULT_INSTANCE}
  type: text
- name: pipeline-debug
  value: "0"
  type: text
