version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - app-repo
    - tekton-catalog-repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'key-management-admin-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  app-repo:
    service_id: >
      $env.source_provider ? $env.source_provider : 'githubconsolidated'
    parameters:
      repo_name: 'key-management-admin-toolchain-{{timestamp}}'
      repo_url: >
        $env.type === 'link' ?
          $env.app_repo : 'https://github.com/open-toolchain/key-management-admin-toolchain'
      source_repo_url: >
        $env.type === 'fork' || $env.type === 'clone' ?
          $env.app_repo : 'https://github.com/open-toolchain/key-management-admin-toolchain'
      type: $env.type || 'link'
      has_issues: false
      enable_traceability: false
      legal: true
  tekton-catalog-repo:
    service_id: >
      $env.source_provider ? $env.source_provider : 'githubconsolidated'
    parameters:
      repo_name: 'common-tekton-tasks-{{timestamp}}'
      repo_url: >
        $env.type === 'link' ?
          $env.app_repo : 'https://github.com/open-toolchain/tekton-catalog'
      source_repo_url: >
        $env.type === 'fork' || $env.type === 'clone' ?
          $env.app_repo : 'https://github.com/open-toolchain/tekton-catalog'
      type: $env.type || 'link'
      has_issues: false
      enable_traceability: false
      legal: true
  build:
    service_id: pipeline
    parameters:
      services:
        - app-repo
      name: '{{services.app-repo.parameters.repo_name}}'
      ui-pipeline: true
      type: tekton
      configuration:
        content:
          $text: pipeline_tekton.yml
        env:
          APP_REPO: app-repo
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          DEV_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          DEV_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          VAULT_INSTANCE: '{{form.pipeline.parameters.vault_name}}'
          BUILD_SIGNER: '{{form.pipeline.parameters.build_signer}}'
          VALIDATION_SIGNER: '{{form.pipeline.parameters.validation_signer}}'
          TEKTON_CATALOG_REPO: tekton-catalog-repo
          APP_REPO_FULL: 'https://github.com/huayuenh/test_key'
        execute: false
form:
  pipeline:
    parameters:
      app-name: '{{services.app-repo.parameters.repo_name}}'
      vault_name: ''
      build_signer: 'devops-build'
      validation_signer: 'devops-validation'
    schema:
      $ref: deploy.json
