---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: create-validate-key
spec:
  params:
    - name: toolchain-apikey
      description: the ibmcloud api key
    - name: repository
      description: target repository
    - name: branch
      description: the branch for the git repo
    - name: revision
      description: the branch for the git repo
    - name: registry-namespace
      description: the registry namespace
    - name: resource-group
      description: The resource group
    - name: pipeline-debug
      default: "0"
    - name: region
      description: the ibmcloud  region
      default: us-south
    - name: vault-name
      description: The name of the Key Protect instance
    - name: validation-signer
      description: The validation signer
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: api-key
          value: $(params.toolchain-apikey)
        - name: region
          value: $(params.region)
        - name: vault-name
          value: $(params.vault-name)
        - name: signer
          value: $(params.validation-signer)
        - name: resource-group
          value: $(params.resource-group)
        - name: registry-namespace
          value: $(params.registry-namespace)
        - name: branch
          value: $(params.branch)
        - name: repository-integration
          value: $(params.repository-integration)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: key-validate-binding
spec:
  params:
    - name: repository
      value: "$params.repository"
    - name: branch
      value: "$params.branch"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: key-validate-listener
spec:
  triggers:
    - binding:
        name: key-validate-binding
      template:
        name: create-validate-key